import React from 'react';
import { ProductRecord } from '../types/plm';
import { X, FileText, CheckCircle2, AlertTriangle, Printer, Download, ShieldAlert, Cpu } from 'lucide-react';

interface ECRModalProps {
  product: ProductRecord | null;
  onClose: () => void;
}

export const ECRModal: React.FC<ECRModalProps> = ({ product, onClose }) => {
  if (!product || !product.prediction) return null;

  const pred = product.prediction;
  const isECR = pred.ecrRequired === 'YES';
  const ecrId = `ECR-${product.productId.replace(/[^a-zA-Z0-9]/g, '')}-${new Date().getFullYear()}`;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadDraft = () => {
    const content = `===============================================================
ENGINEERING CHANGE REQUEST (ECR) DRAFT SPECIFICATION
Generated by AI-Driven PLM Decision Engine
Institution: Chennai Institute of Technology - Department of Mechanical Engineering
===============================================================

ECR Tracking ID   : ${ecrId}
Date Initiated    : ${new Date().toLocaleDateString()}
Product Part ID   : ${product.productId}
Product Name      : ${product.productName}
Production Lot    : ${product.batchLot || 'N/A'}

LIFECYCLE PARAMETER SNAPSHOT:
- Design Complexity            : ${product.parameters.designComplexity} / 10
- Manufacturing Defects        : ${product.parameters.manufacturingDefects} / batch
- Supplier Quality Rating      : ${product.parameters.supplierQuality} %
- Field Warranty Claims        : ${product.parameters.warrantyClaims}
- Safety Compliance Score      : ${product.parameters.safetyCompliance} %
- Maintenance Operating Cost   : $${product.parameters.maintenanceCost} / month
- Tool Wear / Telemetry Index  : ${product.parameters.toolWearTelemetry} / 100

AI DECISION ENGINE ASSESSMENT:
- Product Health Score         : ${pred.productHealthScore} / 100
- Lifecycle Risk Category      : ${pred.riskLevel}
- ECR Required Status          : ${pred.ecrRequired}
- Random Forest Model Consensus: ${pred.treeVotes.yes} of ${pred.treeVotes.total} trees (${pred.confidence}% confidence)
- Primary Failure Influencer   : ${pred.primaryInfluencer}

RECOMMENDED ENGINEERING ACTION:
${pred.recommendedAction}

ENGINEERING REVIEW & SIGNOFF WORKFLOW:
Initiated By   : AI PLM Autonomous Change Decision Engine
Reviewed By    : Lead Mechanical Design Engineer
Approved By    : Chief Quality & PLM Architect (PTC Windchill Pending)
Disposition    : [ ] Approved for ECO   [ ] Fast-Track Change   [ ] Rejected
===============================================================`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${ecrId}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm">
      <div className="bg-white rounded-2xl max-w-3xl w-full max-h-[90vh] overflow-y-auto shadow-2xl border border-slate-200">
        {/* Modal Header */}
        <div className="flex items-center justify-between p-5 border-b border-slate-200 bg-slate-50/90 sticky top-0 z-10 backdrop-blur-sm">
          <div className="flex items-center gap-3">
            <div className={`p-2 rounded-xl ${isECR ? 'bg-rose-100 text-rose-700 border border-rose-300' : 'bg-emerald-100 text-emerald-700 border border-emerald-300'}`}>
              {isECR ? <AlertTriangle className="w-5 h-5" /> : <CheckCircle2 className="w-5 h-5" />}
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-bold text-slate-900 text-base">
                  {isECR ? 'Engineering Change Request (ECR) Dossier' : 'Product Health & Lifecycle Assessment'}
                </h3>
                <span className={`px-2 py-0.5 rounded text-xs font-bold ${
                  isECR ? 'bg-rose-100 text-rose-800 border border-rose-300' : 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                }`}>
                  ECR: {pred.ecrRequired}
                </span>
              </div>
              <p className="text-xs text-slate-500 mt-0.5">
                {product.productId} &bull; {product.productName}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-800 hover:bg-slate-100 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 space-y-6 text-sm text-slate-700">
          {/* Top Key Indicator Strip */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <div className="bg-slate-50 p-3 rounded-xl border border-slate-200 shadow-2xs">
              <span className="text-xs text-slate-500 block font-medium">Product Health Score</span>
              <div className="flex items-baseline gap-2 mt-1">
                <span className={`text-2xl font-bold font-mono ${
                  pred.productHealthScore >= 80 ? 'text-emerald-600' :
                  pred.productHealthScore >= 60 ? 'text-amber-600' : 'text-rose-600'
                }`}>
                  {pred.productHealthScore}
                </span>
                <span className="text-xs text-slate-400">/ 100</span>
              </div>
            </div>

            <div className="bg-slate-50 p-3 rounded-xl border border-slate-200 shadow-2xs">
              <span className="text-xs text-slate-500 block font-medium">Lifecycle Risk Level</span>
              <div className="mt-1">
                <span className={`inline-block px-2.5 py-0.5 rounded text-xs font-semibold uppercase ${
                  pred.riskLevel === 'Low' ? 'bg-emerald-50 text-emerald-800 border border-emerald-300' :
                  pred.riskLevel === 'Medium' ? 'bg-amber-50 text-amber-800 border border-amber-300' :
                  'bg-rose-50 text-rose-800 border border-rose-300'
                }`}>
                  {pred.riskLevel} Risk
                </span>
              </div>
            </div>

            <div className="bg-slate-50 p-3 rounded-xl border border-slate-200 shadow-2xs">
              <span className="text-xs text-slate-500 block font-medium">Random Forest Vote</span>
              <div className="flex items-baseline gap-1 mt-1 font-mono">
                <span className="text-xl font-bold text-slate-900">{pred.treeVotes.yes}</span>
                <span className="text-xs text-slate-500">/ {pred.treeVotes.total} trees</span>
              </div>
            </div>

            <div className="bg-slate-50 p-3 rounded-xl border border-slate-200 shadow-2xs">
              <span className="text-xs text-slate-500 block font-medium">Confidence</span>
              <div className="flex items-baseline gap-1 mt-1 font-mono">
                <span className="text-xl font-bold text-slate-900">{pred.confidence}%</span>
              </div>
            </div>
          </div>

          {/* Recommended Engineering Action Card */}
          <div className={`p-4 rounded-xl border ${
            isECR ? 'bg-rose-50/70 border-rose-200' : 'bg-emerald-50/70 border-emerald-200'
          }`}>
            <div className="flex items-center gap-2 mb-1.5">
              <Cpu className="w-4 h-4 text-slate-700" />
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-700">
                AI Prescribed Action &amp; Root Cause Analysis
              </h4>
            </div>
            <p className="text-sm font-semibold text-slate-900 leading-relaxed">
              {pred.recommendedAction}
            </p>
            <div className="mt-2.5 flex items-center gap-2 text-xs text-slate-600">
              <span>Primary Driver:</span>
              <span className="px-2 py-0.5 rounded bg-white text-slate-800 font-mono font-bold border border-slate-300 shadow-2xs">
                {pred.primaryInfluencer}
              </span>
            </div>
          </div>

          {/* 7 Lifecycle Parameters Breakdown */}
          <div>
            <h4 className="text-xs font-bold text-slate-600 uppercase tracking-wider mb-3">
              7 Lifecycle Input Parameters &amp; Stage Risk Breakdown
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
              {pred.lifecycleRisks.map((lr, idx) => (
                <div key={idx} className="bg-slate-50 p-3 rounded-lg border border-slate-200 flex items-center justify-between">
                  <div>
                    <span className="text-[11px] font-semibold text-slate-500 uppercase tracking-wider block">
                      {lr.stage}
                    </span>
                    <span className="text-xs font-semibold text-slate-800">
                      {lr.parameter}
                    </span>
                  </div>
                  <div className="text-right">
                    <span className={`inline-block px-2 py-0.5 rounded text-[11px] font-mono font-semibold ${
                      lr.status === 'Critical' ? 'bg-rose-50 text-rose-800 border border-rose-300' :
                      lr.status === 'Warning' ? 'bg-amber-50 text-amber-800 border border-amber-300' :
                      'bg-slate-100 text-slate-700 border border-slate-300'
                    }`}>
                      {lr.status}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Academic PLM Note */}
          <div className="p-3 bg-slate-50 rounded-lg border border-slate-200 text-xs text-slate-600 leading-relaxed">
            <strong className="text-slate-900">PLM Stage Integration Notice:</strong> This assessment synthesizes design, manufacturing, supply chain, regulatory, and field service feedback. In full deployment, this will feed into PTC Windchill as an automated ECR entry awaiting chief engineer ECO signoff.
          </div>
        </div>

        {/* Modal Footer */}
        <div className="flex items-center justify-between p-4 border-t border-slate-200 bg-slate-50 sticky bottom-0">
          <div className="text-xs text-slate-500 font-mono">
            Dossier ID: {ecrId}
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-white hover:bg-slate-100 text-slate-700 border border-slate-300 transition-colors shadow-2xs"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Dossier</span>
            </button>
            <button
              onClick={handleDownloadDraft}
              className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg text-xs font-semibold bg-slate-900 hover:bg-slate-800 text-white shadow-xs transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download ECR Draft (.txt)</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
